# Generated by Django 5.0.6 on 2024-05-17 09:32

import django.core.validators
import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EntryScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entryScheme_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="IntakeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intakefield_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SponsorField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsorfield_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Std_Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            myapp.models.validate_letters,
                        ],
                    ),
                ),
                (
                    "lastName",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            myapp.models.validate_letters,
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "residence",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            myapp.models.validate_letters,
                        ],
                    ),
                ),
                (
                    "courseField",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.courses"
                    ),
                ),
                (
                    "entryScheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.entryscheme",
                    ),
                ),
                (
                    "intakeField",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.intakefield",
                    ),
                ),
                (
                    "sponsorField",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.sponsorfield",
                    ),
                ),
            ],
        ),
    ]
